using System.Windows.Input;

namespace SimpleTextEditor.Model
{
    public static class ControlInputFactory
    {
        public static ControlInput Convert(Key key)
        {
            var ctrl = Keyboard.Modifiers.HasFlag(ModifierKeys.Control);
            var shift = Keyboard.Modifiers.HasFlag(ModifierKeys.Shift);

            switch (key)
            {
                case Key.Back:
                    return ControlInput.Backspace;
                case Key.PageUp:
                    return ControlInput.PageUp;
                case Key.PageDown:
                    return ControlInput.PageDown;
                case Key.End:
                    return shift ? ControlInput.EndOfDocument : ControlInput.EndOfLine;
                case Key.Home:
                    return shift ? ControlInput.BeginningOfDocument : ControlInput.BeginningOfLine;
                case Key.Left:
                    return ControlInput.CharacterLeft;
                case Key.Up:
                    return ControlInput.LineUp;
                case Key.Right:
                    return ControlInput.CharacterRight;
                case Key.Down:
                    return ControlInput.LineDown;
                case Key.Delete:
                    return ControlInput.DeleteCurrentCharacter;

                // ********Not Used*******
                case Key.None:
                case Key.Cancel:
                case Key.Tab:
                case Key.LineFeed:
                case Key.Clear:
                case Key.Enter:
                //case Key.Return:
                case Key.Pause:
                case Key.Capital:
                //case Key.CapsLock:
                case Key.HangulMode:
                //case Key.KanaMode:
                case Key.JunjaMode:
                case Key.FinalMode:
                case Key.HanjaMode:
                //case Key.KanjiMode:
                case Key.Escape:
                case Key.ImeConvert:
                case Key.ImeNonConvert:
                case Key.ImeAccept:
                case Key.ImeModeChange:
                case Key.Space:
                //case Key.Prior:
                //case Key.Next:
                case Key.Select:
                case Key.Print:
                case Key.Execute:
                case Key.PrintScreen:
                //case Key.Snapshot:
                case Key.Insert:
                case Key.Help:
                case Key.D0:
                case Key.D1:
                case Key.D2:
                case Key.D3:
                case Key.D4:
                case Key.D5:
                case Key.D6:
                case Key.D7:
                case Key.D8:
                case Key.D9:
                case Key.A:
                case Key.B:
                case Key.C:
                case Key.D:
                case Key.E:
                case Key.F:
                case Key.G:
                case Key.H:
                case Key.I:
                case Key.J:
                case Key.K:
                case Key.L:
                case Key.M:
                case Key.N:
                case Key.O:
                case Key.P:
                case Key.Q:
                case Key.R:
                case Key.S:
                case Key.T:
                case Key.U:
                case Key.V:
                case Key.W:
                case Key.X:
                case Key.Y:
                case Key.Z:
                case Key.LWin:
                case Key.RWin:
                case Key.Apps:
                case Key.Sleep:
                case Key.NumPad0:
                case Key.NumPad1:
                case Key.NumPad2:
                case Key.NumPad3:
                case Key.NumPad4:
                case Key.NumPad5:
                case Key.NumPad6:
                case Key.NumPad7:
                case Key.NumPad8:
                case Key.NumPad9:
                case Key.Multiply:
                case Key.Add:
                case Key.Separator:
                case Key.Subtract:
                case Key.Decimal:
                case Key.Divide:
                case Key.F1:
                case Key.F2:
                case Key.F3:
                case Key.F4:
                case Key.F5:
                case Key.F6:
                case Key.F7:
                case Key.F8:
                case Key.F9:
                case Key.F10:
                case Key.F11:
                case Key.F12:
                case Key.F13:
                case Key.F14:
                case Key.F15:
                case Key.F16:
                case Key.F17:
                case Key.F18:
                case Key.F19:
                case Key.F20:
                case Key.F21:
                case Key.F22:
                case Key.F23:
                case Key.F24:
                case Key.NumLock:
                case Key.Scroll:
                case Key.LeftShift:
                case Key.RightShift:
                case Key.LeftCtrl:
                case Key.RightCtrl:
                case Key.LeftAlt:
                case Key.RightAlt:
                case Key.BrowserBack:
                case Key.BrowserForward:
                case Key.BrowserRefresh:
                case Key.BrowserStop:
                case Key.BrowserSearch:
                case Key.BrowserFavorites:
                case Key.BrowserHome:
                case Key.VolumeMute:
                case Key.VolumeDown:
                case Key.VolumeUp:
                case Key.MediaNextTrack:
                case Key.MediaPreviousTrack:
                case Key.MediaStop:
                case Key.MediaPlayPause:
                case Key.LaunchMail:
                case Key.SelectMedia:
                case Key.LaunchApplication1:
                case Key.LaunchApplication2:
                case Key.Oem1:
                //case Key.OemSemicolon:
                case Key.OemPlus:
                case Key.OemComma:
                case Key.OemMinus:
                case Key.OemPeriod:
                case Key.Oem2:
                //case Key.OemQuestion:
                case Key.Oem3:
                //case Key.OemTilde:
                case Key.AbntC1:
                case Key.AbntC2:
                case Key.Oem4:
                //case Key.OemOpenBrackets:
                case Key.Oem5:
                //case Key.OemPipe:
                case Key.Oem6:
                //case Key.OemCloseBrackets:
                case Key.Oem7:
                //case Key.OemQuotes:
                case Key.Oem8:
                case Key.Oem102:
                //case Key.OemBackslash:
                case Key.ImeProcessed:
                case Key.System:
                case Key.DbeAlphanumeric:
                //case Key.OemAttn:
                case Key.DbeKatakana:
                //case Key.OemFinish:
                case Key.DbeHiragana:
                //case Key.OemCopy:
                case Key.DbeSbcsChar:
                //case Key.OemAuto:
                case Key.DbeDbcsChar:
                //case Key.OemEnlw:
                case Key.DbeRoman:
                //case Key.OemBackTab:
                case Key.Attn:
                //case Key.DbeNoRoman:
                case Key.CrSel:
                //case Key.DbeEnterWordRegisterMode:
                case Key.DbeEnterImeConfigureMode:
                //case Key.ExSel:
                case Key.DbeFlushString:
                //case Key.EraseEof:
                case Key.DbeCodeInput:
                //case Key.Play:
                case Key.DbeNoCodeInput:
                //case Key.Zoom:
                case Key.DbeDetermineString:
                //case Key.NoName:
                case Key.DbeEnterDialogConversionMode:
                //case Key.Pa1:
                case Key.OemClear:
                case Key.DeadCharProcessed:
                default:
                    return ControlInput.None;
            }
        }
    }
}
